# fly.toml app configuration file generated for delebotmsg on 2026-07-30T08:46:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'delebotmsg'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[processes]
  app = 'python delebotmsg2.py'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
